'''

This file associates a default priority to each user event
Priorities go from 5 (less critical) to 0 (most critical)

'''

USER_EVENT_NOTIFICATION_NEW_USER=5
USER_EVENT_NOTIFICATION_NEW_AGENT=5
USER_EVENT_NOTIFICATION_NEW_DATASOURCE=5
USER_EVENT_NOTIFICATION_NEW_DATAPOINT=5
USER_EVENT_NOTIFICATION_NEW_WIDGET=5
USER_EVENT_NOTIFICATION_NEW_DASHBOARD=5
USER_EVENT_NOTIFICATION_NEW_CIRCLE=5
USER_EVENT_NOTIFICATION_NEW_SNAPSHOT_SHARED=5
USER_EVENT_NOTIFICATION_NEW_SNAPSHOT_SHARED_WITH_ME=5

USER_EVENT_INTERVENTION_DATAPOINT_IDENTIFICATION = 2
