MODULES = 'modules'
MODULE_ENABLED = 'enabled'
SAMPLES_OUTPUT_PATH = 'output_path'
SAMPLES_INPUT_PATH = 'input_path'
CASS_KEYSPACE = 'cassandra_keyspace'
CASS_SERVLIST = 'cassandra_server_list'
CASS_POOLSIZE = 'cassandra_pool_size'
SQL_URI = 'sql_uri'