MODULES = 'modules'
MODULE_ENABLED = 'enabled'
CASS_KEYSPACE = 'cassandra_keyspace'
CASS_SERVLIST = 'cassandra_server_list'
CASS_POOLSIZE = 'cassandra_pool_size'
MESSAGE_BROKER='message_broker'
PLOT_DEST_DIR='plot_destination_directory'
