STATE_VALUE_AGENT_DELETED = 0
STATE_VALUE_AGENT_ACTIVE = 1

STATE_VALUE_USER_DELETED = 0
STATE_VALUE_USER_ACTIVE = 1

STATE_VALUE_DATASOURCE_DELETED = 0
STATE_VALUE_DATASOURCE_ACTIVE = 1

STATE_VALUE_SAMPLE_INITIAL = 0

STATE_DESCRIPTION_AGENT_DELETED = "Agent deleted from system"
STATE_DESCRIPTION_AGENT_ACTIVE = "Active Agent"

STATE_DESCRIPTION_USER_DELETED = "User deleted from system"
STATE_DESCRIPTION_USER_ACTIVE = "Active User"

STATE_DESCRIPTION_DATASOURCE_DELETED = "Datasource deleted from system"
STATE_DESCRIPTION_DATASOURCE_ACTIVE = "Active Datasource"

STATE_DESCRIPTION_SAMPLE_INITIAL = "Sample just arrived to the system"




