TYPE_VALUE_AGENT_DEFAULT = 0
TYPE_VALUE_USER_DEFAULT = 0
TYPE_VALUE_DATASOURCE_DEFAULT = 0
TYPE_VALUE_SAMPLE_DEFAULT = 0

TYPE_DESCRIPTION_USER_DEFAULT = "Default Plan User"
TYPE_DESCRIPTION_AGENT_DEFAULT = "Default type Agent"
TYPE_DESCRIPTION_DATASOURCE_DEFAULT = "Default type datasource"
TYPE_DESCRIPTION_SAMPLE_DEFAULT = "Default type sample"
